# La revisión bibliográfica {#sec-revision}

Cuando nos enfrentamos a un trabajo de investigación un paso imprescindible es la **revisión bibliográfica**. De su nombre podemos deducir que consiste en revisar los recursos -bibliográficos- existentes sobre un tema concreto, 

Mirar mas enlaces en @sec-links

Una revisión bibliográfica tiene un papel fundamental en el avance de la ciencia, 

Las revisiones bibliográficas sirven para: 

- Proporciona un marco teórico y metodoloógico que permite hacer aportaciones propias e incluso ser innovadores al afrontar nuevas investigaciones.

- Son la base de productos académicos tales como los estados de la cuestión y los trabajos de revisión. En algunos casos son también la razón de ser de algunas tipologías de TFM. 

- Evitan el riesgo de repetir investigaciones o de utilizar teorías obsoletas o desacreditadas. 

- Sirven para identificar huecos y oportunidades de investigación. 

- En artículos científicos y en memorias de solicitud de proyectos financiados proporcionan garantías a los evaluadores, ya que demuestran que los autores conocen el campo en el que han llevado a cabo su trabajo.

- En tesis doctorales o de máster, permiten demostrar que los autores son capaces de analizar e interpretar críticamente trabajos científicos.

- Proporcionan acceso a las teorías y conceptos que forman parte de la corriente principal del campo en el que se pretende realizar aportaciones. 


- Aportan la base de la evidencia para el estado de la cuestión y trabajos de revisión 
- Proporcionan ideas y modelos para nuevas investigaciones
- 
- Evitan la repetición de investigaciones y el uso de teorías obsoletas o desacreditadas
- Dan garantías a los evaluadores de que los autores conocen el ámbito de la investigación. 












